modLoader="javafml"
loaderVersion="[36,)"
license="Academic Free License v3.0"

[[mods]]
modId="lotmorestevesremake"
version="1.0.0"
displayName="LotMoreStevesRemake"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="±ÔÇõ, MCreator"

[[dependencies.lotmorestevesremake]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"




